const nf=new Intl.NumberFormat('ko-KR'); let data,selected='005930',ownershipChart,flowChart;
const tone=v=>v>0?'good':v<0?'bad':'warn', signed=v=>`${v>0?'+':''}${nf.format(v)}`;
function metric(id,text,cls){const e=document.getElementById(id);e.textContent=text;e.classList.remove('good','bad','warn');if(cls)e.classList.add(cls)}
function options(percent=false){return{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{labels:{color:'#dce8df'}}},scales:{x:{ticks:{color:'#82958b',maxTicksLimit:12},grid:{color:'rgba(32,54,43,.45)'}},y:{ticks:{color:'#82958b',callback:v=>percent?`${v}%`:nf.format(v)},grid:{color:'rgba(32,54,43,.7)'}}}}}
function render(){const stock=data.stocks[selected],rows=stock.records,latest=rows.at(-1),prev=rows.at(-2)||latest,rolling=rows.slice(-20).reduce((s,r)=>s+(r.foreignNetShares||0),0),chartRows=rows.slice(-260),labels=chartRows.map(r=>r.date);
metric('ownership',`${latest.foreignOwnershipPct.toFixed(2)}%`);metric('heldShares',nf.format(latest.foreignHeldShares));metric('dailyNet',signed(latest.foreignNetShares),tone(latest.foreignNetShares));metric('rollingNet',signed(rolling),tone(rolling));document.getElementById('ownershipChange').textContent=`전 거래일 대비 ${(latest.foreignOwnershipPct-prev.foreignOwnershipPct)>=0?'+':''}${(latest.foreignOwnershipPct-prev.foreignOwnershipPct).toFixed(2)}%p`;document.getElementById('dailyNetDate').textContent=latest.date;document.querySelectorAll('#stockTabs button').forEach(b=>b.classList.toggle('active',b.dataset.code===selected));
ownershipChart?.destroy();ownershipChart=new Chart(document.getElementById('ownershipChart'),{type:'line',data:{labels,datasets:[{label:`${stock.name} 외국인 지분율`,data:chartRows.map(r=>r.foreignOwnershipPct),borderColor:'#23e7a5',backgroundColor:'rgba(35,231,165,.12)',fill:true,pointRadius:0,borderWidth:2,tension:.15}]},options:options(true)});
flowChart?.destroy();flowChart=new Chart(document.getElementById('flowChart'),{type:'bar',data:{labels,datasets:[{label:'외국인 순매수(주)',data:chartRows.map(r=>r.foreignNetShares),backgroundColor:chartRows.map(r=>r.foreignNetShares>=0?'rgba(0,192,118,.72)':'rgba(240,138,138,.72)')}]},options:options()});
document.getElementById('foreignRows').innerHTML=rows.slice().reverse().map(r=>`<tr><td>${r.date}</td><td>${nf.format(r.close)}</td><td class="${tone(r.foreignNetShares)}">${signed(r.foreignNetShares)}</td><td>${nf.format(r.foreignHeldShares)}</td><td>${r.foreignOwnershipPct.toFixed(2)}%</td></tr>`).join('')}
async function init(){const res=await fetch('./foreign_flow_data.json',{cache:'no-store'});if(!res.ok)throw Error(res.status);data=await res.json();document.getElementById('foreignUpdatedAt').textContent=`Updated: ${new Date(data.updatedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}`;document.getElementById('stockTabs').innerHTML=Object.values(data.stocks).map(s=>`<button class="chip ${s.code===selected?'active':''}" data-code="${s.code}">${s.name}</button>`).join('');document.getElementById('stockTabs').onclick=e=>{if(e.target.dataset.code){selected=e.target.dataset.code;render()}};render()}
init().catch(e=>{console.error(e);document.querySelector('.foreign-dashboard').insertAdjacentHTML('beforeend','<p class="note bad">외국인 수급 데이터를 불러오지 못했어.</p>')});
