const nf=new Intl.NumberFormat('ko-KR');
const PERIODS=[['7D',7],['30D',30],['90D',90],['180D',180],['1Y',365]];
let data,selected='005930',ownershipPeriod='ALL',flowPeriod='90D',tablePeriod='30D',ownershipChart,flowChart;
const tone=v=>v>0?'good':v<0?'bad':'warn', signed=v=>`${v>0?'+':''}${nf.format(v)}`;
const periodDays=key=>PERIODS.find(([label])=>label===key)?.[1]||null;
function filtered(rows,key){const days=periodDays(key);if(!days)return rows;const end=new Date(`${rows.at(-1).date}T00:00:00`),start=new Date(end);start.setDate(start.getDate()-days+1);return rows.filter(r=>new Date(`${r.date}T00:00:00`)>=start)}
function totals(rows){let buys=0,sells=0,net=0;for(const r of rows){const v=r.foreignNetShares||0;net+=v;if(v>0)buys+=v;else sells+=Math.abs(v)}return{buys,sells,net}}
function cumulative(rows){let sum=0;return rows.map(r=>sum+=(r.foreignNetShares||0))}
function summaryText(rows){const t=totals(rows);return `<span class="summary-item">순매수일 합계 <strong class="summary-buy">${nf.format(t.buys)}주</strong></span><span class="summary-divider">·</span><span class="summary-item">순매도일 합계 <strong class="summary-sell">${nf.format(t.sells)}주</strong></span><span class="summary-divider">·</span><span class="summary-item">순합계 <strong class="summary-net ${tone(t.net)}">${signed(t.net)}주</strong></span>`}
function metric(id,text,cls){const e=document.getElementById(id);e.textContent=text;e.classList.remove('good','bad','warn');if(cls)e.classList.add(cls)}
function tabs(id,active,includeAll,handler){const items=includeAll?[['ALL',null],...PERIODS]:PERIODS;const root=document.getElementById(id);root.innerHTML=items.map(([k])=>`<button class="chip ${k===active?'active':''}" data-period="${k}">${k}</button>`).join('');root.onclick=e=>{if(e.target.dataset.period)handler(e.target.dataset.period)}}
function baseOptions(percent=false){return{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{labels:{color:'#dce8df'}},zoom:{pan:{enabled:true,mode:'x'},zoom:{wheel:{enabled:true,speed:.08},pinch:{enabled:true},mode:'x'}}},scales:{x:{ticks:{color:'#82958b',maxTicksLimit:12},grid:{color:'rgba(32,54,43,.45)'}},y:{ticks:{color:'#82958b',callback:v=>percent?`${v}%`:nf.format(v)},grid:{color:'rgba(32,54,43,.7)'}}}}}
function render(){const stock=data.stocks[selected],rows=stock.records,latest=rows.at(-1),prev=rows.at(-2)||latest,flowRows=filtered(rows,flowPeriod),tableRows=filtered(rows,tablePeriod),flowTotals=totals(flowRows);
metric('ownership',`${latest.foreignOwnershipPct.toFixed(2)}%`);metric('heldShares',nf.format(latest.foreignHeldShares));metric('dailyNet',signed(latest.foreignNetShares),tone(latest.foreignNetShares));metric('rollingNet',signed(flowTotals.net),tone(flowTotals.net));document.getElementById('rollingPeriod').textContent=`${flowPeriod} 순합계`;document.getElementById('ownershipChange').textContent=`전 거래일 대비 ${(latest.foreignOwnershipPct-prev.foreignOwnershipPct)>=0?'+':''}${(latest.foreignOwnershipPct-prev.foreignOwnershipPct).toFixed(2)}%p`;document.getElementById('dailyNetDate').textContent=latest.date;document.querySelectorAll('#stockTabs button').forEach(b=>b.classList.toggle('active',b.dataset.code===selected));
tabs('ownershipPeriods',ownershipPeriod,true,k=>{ownershipPeriod=k;render()});tabs('flowPeriods',flowPeriod,false,k=>{flowPeriod=k;render()});tabs('tablePeriods',tablePeriod,false,k=>{tablePeriod=k;render()});
const ownRows=filtered(rows,ownershipPeriod);ownershipChart?.destroy();ownershipChart=new Chart(document.getElementById('ownershipChart'),{type:'line',data:{labels:ownRows.map(r=>r.date),datasets:[{label:`${stock.name} 외국인 지분율`,data:ownRows.map(r=>r.foreignOwnershipPct),borderColor:'#23e7a5',backgroundColor:'rgba(35,231,165,.12)',fill:true,pointRadius:0,borderWidth:2,tension:.15}]},options:baseOptions(true)});
const flowOptions=baseOptions(false);flowOptions.scales.y.title={display:true,text:'일별 순매수(주)',color:'#82958b'};flowOptions.scales.y1={position:'right',ticks:{color:'#8ea2ff',callback:v=>nf.format(v)},grid:{drawOnChartArea:false},title:{display:true,text:'기간 누적(주)',color:'#8ea2ff'}};
const cumulativeNet=cumulative(flowRows);flowChart?.destroy();flowChart=new Chart(document.getElementById('flowChart'),{data:{labels:flowRows.map(r=>r.date),datasets:[{type:'bar',label:'일별 순매수·순매도',data:flowRows.map(r=>r.foreignNetShares),backgroundColor:flowRows.map(r=>r.foreignNetShares>=0?'rgba(0,192,118,.72)':'rgba(240,138,138,.72)'),yAxisID:'y'},{type:'line',label:'선택 기간 누적 순매수',data:cumulativeNet,borderColor:'#8ea2ff',backgroundColor:'rgba(142,162,255,.15)',pointRadius:0,borderWidth:2,tension:.12,yAxisID:'y1'}]},options:flowOptions});
document.getElementById('flowSummary').innerHTML=summaryText(flowRows);document.getElementById('tableSummary').innerHTML=summaryText(tableRows);
const tableCum=cumulative(tableRows);document.getElementById('foreignRows').innerHTML=tableRows.map((r,i)=>({...r,cum:tableCum[i]})).reverse().map(r=>`<tr><td>${r.date}</td><td>${nf.format(r.close)}</td><td class="${tone(r.foreignNetShares)}">${signed(r.foreignNetShares)}</td><td class="${tone(r.cum)}">${signed(r.cum)}</td><td>${nf.format(r.foreignHeldShares)}</td><td>${r.foreignOwnershipPct.toFixed(2)}%</td></tr>`).join('')}
async function init(){const res=await fetch('./foreign_flow_data.json',{cache:'no-store'});if(!res.ok)throw Error(res.status);data=await res.json();document.getElementById('foreignUpdatedAt').textContent=`Updated: ${new Date(data.updatedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}`;document.getElementById('stockTabs').innerHTML=Object.values(data.stocks).map(s=>`<button class="chip ${s.code===selected?'active':''}" data-code="${s.code}">${s.name}</button>`).join('');document.getElementById('stockTabs').onclick=e=>{if(e.target.dataset.code){selected=e.target.dataset.code;render()}};render()}
init().catch(e=>{console.error(e);document.querySelector('.foreign-dashboard').insertAdjacentHTML('beforeend','<p class="note bad">외국인 수급 데이터를 불러오지 못했어.</p>')});
